### ISSUE TITLE
Issue with Colours

### ISSUE THREAD

**Issue by Jake-GH** [Ocoras/tango-syntax#1]
I have found that the Plum colour (#75507b) does not actually taste like plum when licking the monitor. I have tried multiple monitors and I can confirm it is not a hardware issue. It must be a problem with the code.

Please fix ASAP.

Regards,
Jake

**Comment by davidswarbrick** [comment]
Hi Jake,

The names of the colours were chosen by the Tango Project (and may not reflect their taste), I think you will find the other colours taste the same.
You may find [this video](https://www.youtube.com/watch?v=UBS4Gi1y_nc) helpful.

Regards,
David
